name: multsample
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - biopet-extractadaptersfastqc==0.2
  - biopet-sampleconfig==0.2
  - picard==2.18.7
  - cutadapt==1.16
  - fastqc==0.11.7
  - biopet-scatterregions==0.1
  - samtools==1.8
  - bwa==0.7.17
  - biopet-seqstat==0.1
  - biopet-validatefastq==0.1.1
